# Generated by Django 5.0.2 on 2024-02-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField(max_length=10, verbose_name="rank")),
                ("title", models.CharField(max_length=64, verbose_name="Title")),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="username")),
                ("password", models.CharField(max_length=32, verbose_name="password")),
                ("age", models.IntegerField(max_length=10, verbose_name="age")),
            ],
        ),
    ]
