# Generated by Django 5.0.2 on 2024-02-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="rank",
            field=models.IntegerField(verbose_name="rank"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="age",
            field=models.IntegerField(verbose_name="age"),
        ),
    ]
