# Generated by Django 5.0.2 on 2024-02-25 15:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0003_music_arrow_music_artist_music_pic_music_weeks_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="music",
            name="rank",
        ),
    ]
