# Generated by Django 5.0.2 on 2024-02-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0005_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="number_of_votes",
            field=models.IntegerField(default=0, verbose_name="Number of Votes"),
        ),
        migrations.AddField(
            model_name="music",
            name="total_score",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Total Score"
            ),
        ),
    ]
