# Generated by Django 5.0.2 on 2024-02-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0007_alter_userinfo_options_alter_userinfo_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
