# Generated by Django 5.0.2 on 2024-02-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0008_alter_userinfo_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="total_score",
            field=models.FloatField(
                default=0.0, max_length=10, verbose_name="Total Score"
            ),
        ),
    ]
