# Generated by Django 5.0.2 on 2024-02-28 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0010_alter_rating_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="music",
            name="arrow",
        ),
    ]
