# Generated by Django 5.0.2 on 2024-02-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0011_remove_music_arrow"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="profile_info",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="profile_info"
            ),
        ),
    ]
