# Generated by Django 5.0 on 2024-03-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0012_userinfo_profile_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="avatar",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="avatar"
            ),
        ),
    ]
