# Generated by Django 5.0 on 2024-03-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0016_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Chart Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="US_TopMusic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("artist", models.CharField(max_length=255)),
                ("album", models.CharField(blank=True, max_length=255, null=True)),
                ("cover_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("user", "music")},
        ),
    ]
