# Generated by Django 5.0 on 2024-03-03 09:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0017_chart_us_topmusic_alter_rating_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="us_topmusic",
            unique_together={("title", "artist")},
        ),
    ]
