# Generated by Django 5.0 on 2024-03-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0019_topmusic_delete_us_topmusic"),
    ]

    operations = [
        migrations.CreateModel(
            name="US_TopMusic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("artist", models.CharField(max_length=255)),
                ("album", models.CharField(blank=True, max_length=255, null=True)),
                ("cover_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("title", "artist")},
            },
        ),
        migrations.DeleteModel(
            name="TopMusic",
        ),
    ]
