# Generated by Django 5.0 on 2024-03-03 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0020_us_topmusic_delete_topmusic"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="us_topmusic",
            unique_together=set(),
        ),
    ]
