# Generated by Django 5.0 on 2024-03-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0021_alter_us_topmusic_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="us_topmusic",
            name="region",
            field=models.CharField(
                choices=[
                    ("US", "United States"),
                    ("UK", "British"),
                    ("AU", "Australia"),
                ],
                default="US",
                max_length=2,
            ),
        ),
    ]
