# Generated by Django 5.0 on 2024-03-09 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0022_us_topmusic_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="Moments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Comment Time"
                    ),
                ),
                (
                    "image_urls",
                    models.TextField(blank=True, null=True, verbose_name="Image URLs"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
