# Generated by Django 4.2.1 on 2024-03-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0023_moments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moments",
            name="image_urls",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
