# Generated by Django 4.2.1 on 2024-03-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0024_alter_moments_image_urls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moments",
            name="image_urls",
            field=models.JSONField(default=list),
        ),
    ]
