# Generated by Django 4.2.1 on 2024-03-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0025_alter_moments_image_urls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moments",
            name="image_urls",
            field=models.TextField(blank=True, null=True, verbose_name="Image URLs"),
        ),
    ]
