# Generated by Django 4.2.1 on 2024-03-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0027_alter_moments_image_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="us_topmusic",
            name="rank",
            field=models.IntegerField(default=0),
        ),
    ]
