# Generated by Django 4.2.1 on 2024-03-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0028_us_topmusic_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="moments",
            name="likes_count",
            field=models.IntegerField(default=0, verbose_name="Likes Count"),
        ),
    ]
