# Generated by Django 5.0.3 on 2024-05-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0034_playlist_playlistmusic"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="playlist_cover",
            field=models.FileField(
                blank=True,
                default="playlist_cover/default.png",
                max_length=256,
                null=True,
                upload_to="playlist_cover/",
                verbose_name="avatar",
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="track_number",
            field=models.PositiveIntegerField(default=0, verbose_name="Track Number"),
        ),
    ]
