# Generated by Django 5.0.3 on 2024-05-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0036_alter_playlist_playlist_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="playlist_cover",
            field=models.ImageField(
                blank=True,
                default="https://musictop-bucket.s3.ap-southeast-2.amazonaws.com/default.jpeg",
                max_length=512,
                null=True,
                upload_to="playlist_cover/",
                verbose_name="playlist_cover",
            ),
        ),
    ]
