# Generated by Django 4.2 on 2024-05-18 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0036_alter_playlist_playlist_cover"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotifiCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time Created"
                    ),
                ),
                ("read", models.BooleanField(default=False, verbose_name="Read")),
                (
                    "types",
                    models.IntegerField(
                        choices=[
                            (0, "Like to post"),
                            (1, "Comment to post"),
                            (2, "Comment to comment"),
                        ],
                        verbose_name="Notification Type",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userinfo",
            name="unread_count",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="NotifiCommentComment",
            fields=[
                (
                    "notifi",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="app01.notificenter",
                        verbose_name="Notification",
                    ),
                ),
                ("p_comment_id", models.IntegerField(verbose_name="Parent Comment ID")),
                ("c_comment_id", models.IntegerField(verbose_name="Child Comment ID")),
            ],
        ),
        migrations.CreateModel(
            name="NotifiPostComment",
            fields=[
                (
                    "notifi",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="app01.notificenter",
                        verbose_name="Notification",
                    ),
                ),
                ("post_id", models.IntegerField(verbose_name="Post ID")),
                ("comment_id", models.IntegerField(verbose_name="Comment ID")),
            ],
        ),
        migrations.AddField(
            model_name="notificenter",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.CreateModel(
            name="NotifiLikesPost",
            fields=[
                (
                    "notifi",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="app01.notificenter",
                        verbose_name="Notification",
                    ),
                ),
                (
                    "like",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.like",
                        verbose_name="Like",
                    ),
                ),
            ],
        ),
    ]
