# Generated by Django 5.0.3 on 2024-05-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0037_alter_playlist_playlist_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="tracks",
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name="PlaylistMusic",
        ),
    ]
