# Generated by Django 5.0.3 on 2024-05-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0038_playlist_tracks_delete_playlistmusic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="description",
            field=models.TextField(
                blank=True, verbose_name="My Favourite Songs of 2024"
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="name",
            field=models.CharField(
                max_length=128, verbose_name="John's Top 100 Playlist"
            ),
        ),
    ]
