# Generated by Django 5.0.3 on 2024-05-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0039_alter_playlist_description_alter_playlist_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Name"),
        ),
    ]
