# Generated by Django 5.0.3 on 2024-06-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0040_alter_playlist_description_alter_playlist_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReactUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="Password")),
            ],
        ),
    ]
