# Generated by Django 5.0.3 on 2024-08-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0042_alter_userinfo_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="playlist_cover",
            field=models.URLField(
                blank=True,
                default="https://musictop-bucket.s3.ap-southeast-2.amazonaws.com/default.jpeg",
                max_length=512,
                null=True,
                verbose_name="playlist_cover",
            ),
        ),
    ]
