# Generated by Django 5.0.3 on 2024-08-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0043_alter_playlist_playlist_cover"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaylistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="Title")),
                ("artist", models.CharField(max_length=128, verbose_name="Artist")),
                (
                    "pic_url",
                    models.URLField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Picture URL",
                    ),
                ),
                (
                    "spotify_uri",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Spotify URI"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="tracks",
        ),
        migrations.AddField(
            model_name="playlist",
            name="tracks",
            field=models.ManyToManyField(
                blank=True, related_name="playlists", to="app01.playlistitem"
            ),
        ),
    ]
