# Generated by Django 5.0.3 on 2024-08-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0044_playlistitem_remove_playlist_tracks_playlist_tracks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="tracks",
            field=models.ManyToManyField(
                blank=True, related_name="app01_playlists", to="app01.playlistitem"
            ),
        ),
        migrations.AlterField(
            model_name="playlistitem",
            name="spotify_uri",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Spotify URI"
            ),
        ),
    ]
