# Generated by Django 5.0.3 on 2024-08-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0046_playlistitem_app01_playl_spotify_636735_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlistitem",
            name="spotify_uri",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                unique=True,
                verbose_name="Spotify URI",
            ),
        ),
    ]
