# Generated by Django 5.0.3 on 2024-08-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0047_alter_playlistitem_spotify_uri"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlistitem",
            name="spotify_uri",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Spotify URI",
            ),
        ),
    ]
