# Generated by Django 5.0.3 on 2024-07-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("react_app", "0002_alter_reactuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reactuser",
            name="username",
            field=models.CharField(default="default_username", max_length=150),
            preserve_default=False,
        ),
    ]
