# Generated by Django 5.0.3 on 2024-07-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("react_app", "0003_alter_reactuser_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reactuser",
            options={},
        ),
        migrations.AlterModelManagers(
            name="reactuser",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="reactuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="reactuser",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="reactuser",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="reactuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="reactuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reactuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reactuser",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
