# Generated by Django 5.0.3 on 2024-08-10 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0045_alter_playlist_tracks_alter_playlistitem_spotify_uri"),
        ("react_app", "0004_alter_reactuser_options_alter_reactuser_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reactuser",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="reactuser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="reactuser",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="reactuser",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="reactuser",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="reactuser",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="reactuser",
            name="user_permissions",
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "playlist_cover",
                    models.URLField(
                        blank=True,
                        default="https://musictop-bucket.s3.ap-southeast-2.amazonaws.com/default.jpeg",
                        max_length=512,
                        null=True,
                        verbose_name="playlist_cover",
                    ),
                ),
                (
                    "track_number",
                    models.PositiveIntegerField(default=0, verbose_name="Track Number"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "tracks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="react_playlists",
                        to="app01.playlistitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="react_playlists",
                        to="react_app.reactuser",
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
