# Generated by Django 5.0.3 on 2024-08-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "react_app",
            "0005_remove_reactuser_date_joined_remove_reactuser_groups_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Description"),
        ),
    ]
